context:
  version: "3.2.0"

package:
  name: tshy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tshy/-/tshy-${{ version }}.tgz
  sha256: 89d69bcea241dca383d1c4ebfbe692477fc7e0e5cfe6dd253c01475228a01263

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "tshy 2>&1 | grep -q \"failed to read package.json\""

about:
  license: BlueOak-1.0.0
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: TypeScript HYbridizer
  homepage: https://github.com/isaacs/tshy
  repository: https://github.com/isaacs/tshy

extra:
  recipe-maintainers:
    - danielnachun
