context:
  version: "3.3.2"

package:
  name: tshy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tshy/-/tshy-${{ version }}.tgz
  sha256: 7f80fa5df1b6d8fe3fc0b0b25827c862ddb117efe18db4a8b98b3f738cdb627f

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "tshy 2>&1 | grep -q \"failed to read package.json\""

about:
  license: BlueOak-1.0.0
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: TypeScript HYbridizer
  homepage: https://github.com/isaacs/tshy
  repository: https://github.com/isaacs/tshy

extra:
  recipe-maintainers:
    - danielnachun
