context:
  version: "3.0.3"

package:
  name: tshy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tshy/-/tshy-${{ version }}.tgz
  sha256: 31cbd29078185d676c036893b23e6eb38ae5062c76dc0d3050dce818bd7106cf

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "tshy 2>&1 | grep -q \"failed to read package.json\""

about:
  license: BlueOak-1.0.0
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: TypeScript HYbridizer
  homepage: https://github.com/isaacs/tshy
  repository: https://github.com/isaacs/tshy

extra:
  recipe-maintainers:
    - danielnachun
