context:
  version: "4.1.2"

package:
  name: tshy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tshy/-/tshy-${{ version }}.tgz
  sha256: bc4a27b36f040e36b721a6fb82202c3821a91f5ae18d4ec4c44e32b91b7206ea

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "tshy 2>&1 | grep -q \"failed to read package.json\""

about:
  license: BlueOak-1.0.0
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: TypeScript HYbridizer
  homepage: https://github.com/isaacs/tshy
  repository: https://github.com/isaacs/tshy

extra:
  recipe-maintainers:
    - danielnachun
