context:
  version: "4.0.0"

package:
  name: tshy
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/tshy/-/tshy-${{ version }}.tgz
  sha256: e67d7b0708bf436ab93d2663b852bed22297481e72ca85bb0c53a8caf741803b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - "tshy 2>&1 | grep -q \"failed to read package.json\""

about:
  license: BlueOak-1.0.0
  license_file:
    - LICENSE.md
    - third-party-licenses.txt
  summary: TypeScript HYbridizer
  homepage: https://github.com/isaacs/tshy
  repository: https://github.com/isaacs/tshy

extra:
  recipe-maintainers:
    - danielnachun
